# Generated by Django 3.0.8 on 2021-01-25 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasesProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la base')),
            ],
            options={
                'verbose_name': 'Bases',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre ')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Sabores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del sabor')),
            ],
            options={
                'verbose_name': 'Sabores',
                'verbose_name_plural': 'Sabores',
            },
        ),
        migrations.CreateModel(
            name='ProduccionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(blank=True, default=0, verbose_name='Total cantidad')),
                ('gramos', models.IntegerField(blank=True, default=0, verbose_name='Total gramos')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_producto', to='produccion.BasesProduccion', verbose_name='base')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Categoria_producto', to='produccion.Categoria')),
                ('sabor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sabor_produccion', to='produccion.Sabores')),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad producida')),
                ('gramos', models.IntegerField(default=0, verbose_name='Gramos unitario')),
                ('total_gramos', models.IntegerField(default=0, verbose_name='Total producido')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_produccion', to='produccion.ProduccionProducto')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producción',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gramos', models.IntegerField(blank=True, verbose_name='Gramos utilizados')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('insumos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Insumos', to='insumos.Insumos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='produccion.ProduccionProducto')),
                ('producto_rela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_to_producto', to='produccion.ProduccionProducto')),
            ],
            options={
                'verbose_name': 'Detalle Produccion',
                'verbose_name_plural': 'Detalle Produccion',
            },
        ),
        migrations.CreateModel(
            name='DetalleBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('porcentaje', models.IntegerField(default=0, verbose_name='Porcentaje')),
                ('isprod', models.BooleanField(default=False, verbose_name='¿Es un producto?')),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base', to='produccion.BasesProduccion')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumo', to='insumos.Insumos')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_base', to='produccion.ProduccionProducto')),
            ],
            options={
                'verbose_name': ('Detalle Base',),
                'verbose_name_plural': 'Detalle Base',
            },
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gramos', models.IntegerField(verbose_name='Gramos')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_consumo', to='produccion.ProduccionProducto')),
            ],
            options={
                'verbose_name': 'Consumo Produccion',
                'verbose_name_plural': 'Consumo Produccion',
            },
        ),
    ]
