# Generated by Django 3.0.8 on 2021-01-25 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('n_factura', models.CharField(blank=True, max_length=256, null=True, verbose_name='Número de factura')),
                ('descuento', models.CharField(blank=True, max_length=100, verbose_name='Descuento aplicado')),
                ('guardado', models.BooleanField(default=False, verbose_name='Guardado')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('valor', models.BigIntegerField(default=0, verbose_name='Valor')),
                ('pedidos', models.ManyToManyField(related_name='Pedidos', to='pedido.Pedidos')),
                ('personas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona_factura', to='personas.Personas')),
            ],
            options={
                'verbose_name': 'Facturas',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
