# Generated by Django 3.0.8 on 2021-01-25 00:04

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo Persona',
                'verbose_name_plural': 'Tipo Persona',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('username', models.CharField(max_length=50, null=True, unique=True, verbose_name='Username')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('clave', models.CharField(blank=True, max_length=6, verbose_name='Clave')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('TipoPersona', models.ManyToManyField(related_name='Tipo_persona', to='personas.TipoPersona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
