# Generated by Django 3.0.8 on 2021-01-25 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de unidad')),
                ('valor', models.FloatField(default=0, verbose_name='¿Valor en gramos?')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidad de medida',
            },
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rendimiento', models.PositiveSmallIntegerField(blank=True, default=100, null=True, verbose_name='Rendimiento(Porc)')),
                ('cantidad', models.IntegerField(blank=True, default=0, verbose_name='Cantidad')),
                ('gramos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gramos últiles')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_medida', to='insumos.Unidad_Medida', verbose_name='unidad de medida')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumo',
            },
        ),
        migrations.CreateModel(
            name='ConsumoInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gramos', models.IntegerField(verbose_name='Gramos')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consumo_insumos', to='insumos.Insumos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(verbose_name='Fecha de compra')),
                ('cantidad', models.IntegerField(blank=True, default=0, verbose_name='Cantidad')),
                ('gramos_unidad', models.IntegerField(blank=True, default=0, verbose_name='Gramos x Unidad')),
                ('precio_unidad', models.IntegerField(blank=True, default=0, verbose_name='Precio x  Unidad')),
                ('gramos_total', models.IntegerField(blank=True, default=0, verbose_name='Gramos Total')),
                ('gramos', models.IntegerField(blank=True, default=0, verbose_name='Gramos Útiles')),
                ('precio', models.IntegerField(blank=True, default=0, verbose_name='Precio Total')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Compra_insumos', to='insumos.Insumos')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad', to='insumos.Unidad_Medida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
