# Generated by Django 3.0.8 on 2021-01-25 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('insumos', '0001_initial'),
        ('preparacion', '0001_initial'),
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('observacion', models.CharField(blank=True, max_length=100, verbose_name='Observacion')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado Cocina')),
                ('facturado', models.BooleanField(default=False, verbose_name='Facturado')),
                ('entrega_cocina', models.BooleanField(default=False, verbose_name='Entrega de Cocina')),
                ('entrega_cliente', models.BooleanField(default=False, verbose_name='Entrega a Cliente')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de preparación')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora de finalizcion')),
                ('hora_entrega', models.TimeField(blank=True, null=True, verbose_name='Hora de entrega')),
                ('cliente_name', models.CharField(blank=True, max_length=100, verbose_name='Cliente')),
                ('valor', models.BigIntegerField(blank=True, default=0, verbose_name='Valor')),
                ('desc_pedido', models.TextField(blank=True, verbose_name='Descripción Pedido')),
                ('condiciones', models.TextField(blank=True, verbose_name='Condiciones Pedido')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignado_a', to='personas.Personas')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preparacion.Productos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ingrediente_name', models.CharField(max_length=100, verbose_name='Ingrediente/Asumo/Adicion')),
                ('gramos', models.IntegerField(blank=True, default=0, verbose_name='Gramos utilizados')),
                ('valor', models.BigIntegerField(blank=True, default=0, verbose_name='Valor')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumo_pedido', to='insumos.Insumos')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.Pedidos')),
                ('produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produccion_pedido', to='produccion.ProduccionProducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoordinacionCocina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Personas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
