# Generated by Django 3.0.8 on 2021-01-25 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('porcentaje', models.IntegerField(default=0, verbose_name='Porcentaje')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_final', models.TimeField(blank=True, null=True, verbose_name='Hora de vencimiento')),
                ('estado', models.BooleanField(default=False, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Promociones y Descuentos',
                'verbose_name_plural': 'Promociones y Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.IntegerField(blank=True, default=0, null=True, verbose_name='precio')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='cantidad')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='stock')),
                ('gramos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Gramos para Helado')),
                ('cantidad_gramos', models.IntegerField(blank=True, default=0, null=True, verbose_name='Bolas de helado')),
                ('timeout', models.IntegerField(blank=True, default=0, null=True, verbose_name='Tiempo de espera')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('facturable', models.BooleanField(default=True, verbose_name='Facturable')),
                ('adicion', models.BooleanField(default=False, verbose_name='Adicion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categoria_productos', to='preparacion.Categoria')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Promocion_de_producto', to='preparacion.Promociones')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor_de_producto', to='preparacion.Proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='InsumosProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('gramos', models.IntegerField(default=0, verbose_name='Gramos a utilizar')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumo_producto', to='insumos.Insumos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_insumo', to='preparacion.Productos')),
            ],
            options={
                'verbose_name': 'InsumosProducto',
                'verbose_name_plural': 'InsumosProducto',
            },
        ),
    ]
