# Generated by Django 3.0.8 on 2021-01-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preparacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumosproducto',
            name='obligatorio',
            field=models.BooleanField(default=False, verbose_name='Obligatorio'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad_gramos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bolas de Helado/Pulpa'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='gramos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Gramos para Helado/Pulpa'),
        ),
    ]
